// Base de datos de juegos bíblicos (Reina-Valera 1960) multi-idioma - CARGA MASIVA v3
export const JUEGOS_MULTI = {
  es: [
    { tipo: "quiz", pregunta: "¿Quién construyó el arca?", opciones: ["Noé", "Moisés", "Abraham", "David"], respuesta: "Noé" },
    { tipo: "versiculo", pregunta: "El Señor es mi ____; nada me faltará", opciones: ["pastor", "escudo", "guía", "refugio"], respuesta: "pastor" },
    { tipo: "personaje", pistas: ["Personaje que derrotó a Goliat"], opciones: ["David", "Saúl", "Salomón", "Sansón"], respuesta: "David" },
    { tipo: "quiz", pregunta: "¿Quién estuvo en el foso de los leones?", opciones: ["Daniel", "Pedro", "Pablo", "José"], respuesta: "Daniel" },
    { tipo: "versiculo", pregunta: "La fe viene por el ____", opciones: ["oír", "ver", "sentir", "creer"], respuesta: "oír" },
    { tipo: "personaje", pistas: ["Personaje que interpretó sueños en Egipto"], opciones: ["José", "Daniel", "Jacobs", "Esaú"], respuesta: "José" },
    { tipo: "quiz", pregunta: "¿Quién negó a Jesús tres veces?", opciones: ["Pedro", "Juan", "Judas", "Tomás"], respuesta: "Pedro" },
    { tipo: "versiculo", pregunta: "Pedid y se os ____", opciones: ["dará", "quitará", "negará", "abrirá"], respuesta: "dará" },
    { tipo: "personaje", pistas: ["Personaje que es llamado padre de la fe"], opciones: ["Abraham", "Noé", "Isaac", "Jacob"], respuesta: "Abraham" },
    { tipo: "quiz", pregunta: "¿Quién fue madre de Jesús?", opciones: ["María", "Marta", "Isabel", "Magdalena"], respuesta: "María" },
    { tipo: "versiculo", pregunta: "Porque de tal manera amó Dios al ____", opciones: ["mundo", "hombre", "pueblo", "reino"], respuesta: "mundo" },
    { tipo: "personaje", pistas: ["Personaje que abrió el Mar Rojo"], opciones: ["Moisés", "Josué", "Aarón", "Gedeón"], respuesta: "Moisés" },
    { tipo: "quiz", pregunta: "¿Quién derrotó a Goliat?", opciones: ["David", "Saúl", "Jonatán", "Josué"], respuesta: "David" },
    { tipo: "versiculo", pregunta: "Lámpara es a mis pies tu ____", opciones: ["palabra", "luz", "ley", "guía"], respuesta: "palabra" },
    { tipo: "personaje", pistas: ["Personaje que fue tragado por un gran pez"], opciones: ["Jonás", "Noé", "Pedro", "Pablo"], respuesta: "Jonás" },
    { tipo: "quiz", pregunta: "¿Quién interpretó sueños en Egipto?", opciones: ["José", "Daniel", "Faraón", "Coperos"], respuesta: "José" },
    { tipo: "versiculo", pregunta: "Bienaventurados los de limpio ____", opciones: ["corazón", "espíritu", "alma", "mente"], respuesta: "corazón" },
    { tipo: "personaje", pistas: ["Personaje que fue famoso por su sabiduría"], opciones: ["Salomón", "David", "Eclesiastés", "Jesús"], respuesta: "Salomón" },
    { tipo: "quiz", pregunta: "¿Quién es llamado padre de la fe?", opciones: ["Abraham", "Isaac", "Jacob", "Moisés"], respuesta: "Abraham" },
    { tipo: "versiculo", pregunta: "En el principio creó Dios los ____ y la tierra", opciones: ["cielos", "mares", "hombres", "animales"], respuesta: "cielos" },
    { tipo: "quiz", pregunta: "¿Quién abrió el Mar Rojo?", opciones: ["Moisés", "Josué", "Aarón", "Aser"], respuesta: "Moisés" },
    { tipo: "versiculo", pregunta: "Todo lo puedo en ____ que me fortalece", opciones: ["Cristo", "Dios", "el Señor", "el Espíritu"], respuesta: "Cristo" },
    { tipo: "quiz", pregunta: "¿Quién fue tragado por un gran pez?", opciones: ["Jonás", "Noé", "Pedro", "Pablo"], respuesta: "Jonás" },
    { tipo: "versiculo", pregunta: "Jehová es mi luz y mi ____", opciones: ["salvación", "fuerza", "guía", "amparo"], respuesta: "salvación" },
    { tipo: "quiz", pregunta: "¿Quién fue famoso por su sabiduría?", opciones: ["Salomón", "David", "Roboam", "Josafat"], respuesta: "Salomón" },
    { tipo: "versiculo", pregunta: "El cielo y la tierra pasarán pero mis ____ no pasarán", opciones: ["palabras", "leyes", "caminos", "promesas"], respuesta: "palabras" },
    { tipo: "quiz", pregunta: "¿Cuántos años pasaron los Israelitas en el desierto?", opciones: ["40", "50", "30", "12"], respuesta: "40" },
    { tipo: "versiculo", pregunta: "Clama a mí y yo te ____", opciones: ["responderé", "ayudaré", "salvaré", "miraré"], respuesta: "responderé" },
    { tipo: "personaje", pistas: ["Fui arrojado a un foso de leones por orar"], opciones: ["Daniel", "Ezequiel", "Jeremías", "Isaías"], respuesta: "Daniel" },
    { tipo: "quiz", pregunta: "¿En qué ciudad nació Jesús?", opciones: ["Belén", "Nazaret", "Jerusalén", "Jericó"], respuesta: "Belén" },
    { tipo: "versiculo", pregunta: "Buscad primero el reino de ____", opciones: ["Dios", "los cielos", "paz", "justicia"], respuesta: "Dios" },
    { tipo: "personaje", pistas: ["Fui el hombre más fuerte de la Biblia"], opciones: ["Sansón", "Goliat", "Gedeón", "David"], respuesta: "Sansón" },
    { tipo: "quiz", pregunta: "¿Cuál es el primer libro de la Biblia?", opciones: ["Génesis", "Éxodo", "Mateo", "Apocalipsis"], respuesta: "Génesis" },
    { tipo: "versiculo", pregunta: "Jehová es mi pastor, nada me ____", opciones: ["faltará", "sobrará", "tirará", "negará"], respuesta: "faltará" },
    { tipo: "personaje", pistas: ["Fui el primer hombre creado"], opciones: ["Adán", "Noé", "Enoc", "Abel"], respuesta: "Adán" },
    { tipo: "quiz", pregunta: "¿Quién traicionó a Jesús con un beso?", opciones: ["Judas", "Pedro", "Tomas", "Mateo"], respuesta: "Judas" },
    { tipo: "versiculo", pregunta: "En el principio era el ____", opciones: ["Verbo", "Mundo", "Hombre", "Espíritu"], respuesta: "Verbo" },
    { tipo: "personaje", pistas: ["Padecí mucha sarna y perdí todo pero no negué a Dios"], opciones: ["Job", "Elías", "Isaías", "Lázaro"], respuesta: "Job" },
    { tipo: "quiz", pregunta: "¿Cuál es el último libro de la Biblia?", opciones: ["Apocalipsis", "Judas", "Hebreos", "Malaquías"], respuesta: "Apocalipsis" },
    { tipo: "versiculo", pregunta: "Jesús lloró. (Juan ____)", opciones: ["11:35", "3:16", "1:1", "14:6"], respuesta: "11:35" },
    { tipo: "quiz", pregunta: "¿Quién fue el hombre que vivió más años?", opciones: ["Matusalén", "Enoc", "Noé", "Adán"], respuesta: "Matusalén" },
    { tipo: "versiculo", pregunta: "Crea en mí, oh Dios, un ____ limpio", opciones: ["corazón", "espíritu", "camino", "alma"], respuesta: "corazón" },
    { tipo: "personaje", pistas: ["Su esposa se convirtió en estatua de sal"], opciones: ["Lot", "Abraham", "Isaac", "Jacob"], respuesta: "Lot" },
    { tipo: "quiz", pregunta: "¿A quién resucitó Jesús a los cuatro días?", opciones: ["Lázaro", "Jairo", "Bartimeo", "Nicodemo"], respuesta: "Lázaro" },
    { tipo: "versiculo", pregunta: "Soportando ____ los unos a los otros", opciones: ["con paciencia", "con amor", "en paz", "en fe"], respuesta: "con amor" },
    { tipo: "personaje", pistas: ["Hizo descender fuego del cielo en el Monte Carmelo"], opciones: ["Elías", "Eliseo", "Isaías", "Jeremías"], respuesta: "Elías" },
    { tipo: "quiz", pregunta: "¿Cuántas plagas envió Dios a Egipto?", opciones: ["10", "12", "7", "40"], respuesta: "10" },
    { tipo: "versiculo", pregunta: "El temor de Jehová es el principio de la ____", opciones: ["sabiduría", "fe", "vida", "paz"], respuesta: "sabiduría" },
    { tipo: "personaje", pistas: ["Bautizó a Jesús en el río Jordán"], opciones: ["Juan el Bautista", "Pedro", "Santiago", "Felipe"], respuesta: "Juan el Bautista" },
    { tipo: "quiz", pregunta: "¿Qué niño fue salvado de un río en una canasta?", opciones: ["Moisés", "José", "Isaac", "Samuel"], respuesta: "Moisés" },
    { tipo: "versiculo", pregunta: "Mas el fruto del Espíritu es ____", opciones: ["amor", "fe", "poder", "sabiduría"], respuesta: "amor" },
    { tipo: "personaje", pistas: ["Construyó el Templo de Jerusalén"], opciones: ["Salomón", "David", "Esdras", "Nehemías"], respuesta: "Salomón" },
    { tipo: "quiz", pregunta: "¿Quién mató a un gigante con cinco piedras lisas?", opciones: ["David", "Saúl", "Jonatán", "Josué"], respuesta: "David" },
    { tipo: "versiculo", pregunta: "Ustedes son la ____ del mundo", opciones: ["luz", "sal", "paz", "vida"], respuesta: "luz" },
    { tipo: "personaje", pistas: ["Tuvo una túnica de muchos colores"], opciones: ["José", "Benjamín", "Rubén", "Judá"], respuesta: "José" },
    { tipo: "quiz", pregunta: "¿Cuál era la profesión de Mateo antes de seguir a Jesús?", opciones: ["Publicano", "Pescador", "Carpintero", "Sacerdote"], respuesta: "Publicano" },
    { tipo: "versiculo", pregunta: "Yo soy el camino, la ____ y la vida", opciones: ["verdad", "luz", "puerta", "paz"], respuesta: "verdad" },
    { tipo: "personaje", pistas: ["Fue llevado al cielo en un torbellino"], opciones: ["Elías", "Enoc", "Moisés", "Juan"], respuesta: "Elías" },
    { tipo: "quiz", pregunta: "¿Quién escribió la mayoría del Nuevo Testamento?", opciones: ["Pablo", "Juan", "Pedro", "Lucas"], respuesta: "Pablo" },
    { tipo: "versiculo", pregunta: "Nada hay imposible para ____", opciones: ["Dios", "el hombre", "la fe", "la oración"], respuesta: "Dios" }
  ],
  en: [
    { tipo: "quiz", pregunta: "Who built the ark?", opciones: ["Noah", "Moses", "Abraham", "David"], respuesta: "Noah" },
    { tipo: "versiculo", pregunta: "The Lord is my ____; I shall not want", opciones: ["shepherd", "shield", "guide", "refuge"], respuesta: "shepherd" },
    { tipo: "personaje", pistas: ["Character who defeated Goliath"], opciones: ["David", "Saul", "Solomon", "Samson"], respuesta: "David" },
    { tipo: "quiz", pregunta: "Who was in the lions' den?", opciones: ["Daniel", "Peter", "Paul", "Joseph"], respuesta: "Daniel" },
    { tipo: "versiculo", pregunta: "Faith comes by ____", opciones: ["hearing", "seeing", "feeling", "believing"], respuesta: "hearing" },
    { tipo: "personaje", pistas: ["Character who interpreted dreams in Egypt"], opciones: ["Joseph", "Daniel", "Jacob", "Esau"], respuesta: "Joseph" },
    { tipo: "quiz", pregunta: "Who denied Jesus three times?", opciones: ["Peter", "John", "Judas", "Thomas"], respuesta: "Peter" },
    { tipo: "versiculo", pregunta: "Ask and it shall be ____ to you", opciones: ["given", "taken", "denied", "opened"], respuesta: "given" },
    { tipo: "personaje", pistas: ["Character called the father of faith"], opciones: ["Abraham", "Noah", "Isaac", "Jacob"], respuesta: "Abraham" },
    { tipo: "quiz", pregunta: "Who was the mother of Jesus?", opciones: ["Mary", "Martha", "Elizabeth", "Magdalene"], respuesta: "Mary" },
    { tipo: "versiculo", pregunta: "For God so loved the ____", opciones: ["world", "man", "people", "kingdom"], respuesta: "world" },
    { tipo: "personaje", pistas: ["Character who parted the Red Sea"], opciones: ["Moses", "Joshua", "Aaron", "Gideon"], respuesta: "Moses" },
    { tipo: "quiz", pregunta: "Who defeated Goliath?", opciones: ["David", "Saul", "Jonathan", "Joshua"], respuesta: "David" },
    { tipo: "versiculo", pregunta: "Your ____ is a lamp to my feet", opciones: ["word", "light", "law", "guide"], respuesta: "word" },
    { tipo: "personaje", pistas: ["Character swallowed by a great fish"], opciones: ["Jonah", "Noah", "Peter", "Paul"], respuesta: "Jonah" },
    { tipo: "quiz", pregunta: "Who interpreted dreams in Egypt?", opciones: ["Joseph", "Daniel", "Pharaoh", "Cupbearer"], respuesta: "Joseph" },
    { tipo: "versiculo", pregunta: "Blessed are the pure in ____", opciones: ["heart", "spirit", "soul", "mind"], respuesta: "heart" },
    { tipo: "personaje", pistas: ["Character famous for wisdom"], opciones: ["Solomon", "David", "Ecclesiastes", "Jesus"], respuesta: "Solomon" },
    { tipo: "quiz", pregunta: "Who is called the father of faith?", opciones: ["Abraham", "Isaac", "Jacob", "Moses"], respuesta: "Abraham" },
    { tipo: "versiculo", pregunta: "In the beginning God created the ____ and the earth", opciones: ["heavens", "seas", "men", "animals"], respuesta: "heavens" },
    { tipo: "quiz", pregunta: "Who parted the Red Sea?", opciones: ["Moses", "Joshua", "Aaron", "Asher"], respuesta: "Moses" },
    { tipo: "versiculo", pregunta: "I can do all things through ____ who strengthens me", opciones: ["Christ", "God", "the Lord", "the Spirit"], respuesta: "Christ" },
    { tipo: "quiz", pregunta: "Who was swallowed by a great fish?", opciones: ["Jonah", "Noah", "Peter", "Paul"], respuesta: "Jonah" },
    { tipo: "versiculo", pregunta: "The Lord is my light and my ____", opciones: ["salvation", "strength", "guide", "refuge"], respuesta: "salvation" },
    { tipo: "quiz", pregunta: "Who was famous for his wisdom?", opciones: ["Solomon", "David", "Rehoboam", "Jehoshaphat"], respuesta: "Solomon" },
    { tipo: "versiculo", pregunta: "Heaven and earth will pass away, but my ____ will not pass away", opciones: ["words", "laws", "ways", "promises"], respuesta: "words" },
    { tipo: "quiz", pregunta: "How many years did the Israelites spend in the desert?", opciones: ["40", "50", "30", "12"], respuesta: "40" },
    { tipo: "versiculo", pregunta: "Call to me and I will ____ you", opciones: ["answer", "help", "save", "look"], respuesta: "answer" },
    { tipo: "personaje", pistas: ["I was thrown into a lions' den for praying"], opciones: ["Daniel", "Ezekiel", "Jeremiah", "Isaiah"], respuesta: "Daniel" },
    { tipo: "quiz", pregunta: "In which city was Jesus born?", opciones: ["Bethlehem", "Nazareth", "Jerusalem", "Jericho"], respuesta: "Bethlehem" },
    { tipo: "versiculo", pregunta: "Seek first the kingdom of ____", opciones: ["God", "heaven", "peace", "justice"], respuesta: "God" },
    { tipo: "personaje", pistas: ["I was the strongest man in the Bible"], opciones: ["Samson", "Goliath", "Gideon", "David"], respuesta: "Samson" },
    { tipo: "quiz", pregunta: "What is the first book of the Bible?", opciones: ["Genesis", "Exodus", "Matthew", "Revelation"], respuesta: "Genesis" },
    { tipo: "versiculo", pregunta: "The Lord is my shepherd, I shall not ____", opciones: ["want", "waste", "lose", "denied"], respuesta: "want" },
    { tipo: "personaje", pistas: ["I was the first man created"], opciones: ["Adam", "Noah", "Enoch", "Abel"], respuesta: "Adam" },
    { tipo: "quiz", pregunta: "Who betrayed Jesus with a kiss?", opciones: ["Judas", "Peter", "Thomas", "Matthew"], respuesta: "Judas" },
    { tipo: "versiculo", pregunta: "In the beginning was the ____", opciones: ["Word", "World", "Man", "Spirit"], respuesta: "Word" },
    { tipo: "personaje", pistas: ["I suffered much but did not deny God"], opciones: ["Job", "Elijah", "Isaiah", "Lazarus"], respuesta: "Job" },
    { tipo: "quiz", pregunta: "What is the last book of the Bible?", opciones: ["Revelation", "Jude", "Hebrews", "Malachi"], respuesta: "Revelation" },
    { tipo: "versiculo", pregunta: "Jesus wept. (John ____)", opciones: ["11:35", "3:16", "1:1", "14:6"], respuesta: "11:35" },
    { tipo: "quiz", pregunta: "Who was the oldest man in the Bible?", opciones: ["Methuselah", "Enoch", "Noah", "Adam"], respuesta: "Methuselah" },
    { tipo: "versiculo", pregunta: "Create in me a clean ____, O God", opciones: ["heart", "spirit", "way", "soul"], respuesta: "heart" },
    { tipo: "personaje", pistas: ["His wife turned into a pillar of salt"], opciones: ["Lot", "Abraham", "Isaac", "Jacob"], respuesta: "Lot" },
    { tipo: "quiz", pregunta: "Who did Jesus raise from the dead after four days?", opciones: ["Lazarus", "Jairus", "Bartimaeus", "Nicodemus"], respuesta: "Lazarus" },
    { tipo: "versiculo", pregunta: "Bearing with one another in ____", opciones: ["love", "patience", "peace", "faith"], respuesta: "love" },
    { tipo: "personaje", pistas: ["He called down fire from heaven on Mount Carmel"], opciones: ["Elijah", "Elisha", "Isaiah", "Jeremiah"], respuesta: "Elijah" },
    { tipo: "quiz", pregunta: "How many plagues did God send to Egypt?", opciones: ["10", "12", "7", "40"], respuesta: "10" },
    { tipo: "versiculo", pregunta: "The fear of the Lord is the beginning of ____", opciones: ["wisdom", "faith", "life", "peace"], respuesta: "wisdom" },
    { tipo: "personaje", pistas: ["He baptized Jesus in the Jordan River"], opciones: ["John the Baptist", "Peter", "James", "Philip"], respuesta: "John the Baptist" },
    { tipo: "quiz", pregunta: "Which baby was saved from a river in a basket?", opciones: ["Moses", "Joseph", "Isaac", "Samuel"], respuesta: "Moses" },
    { tipo: "versiculo", pregunta: "But the fruit of the Spirit is ____", opciones: ["love", "faith", "power", "wisdom"], respuesta: "love" },
    { tipo: "personaje", pistas: ["He built the Temple in Jerusalem"], opciones: ["Solomon", "David", "Ezra", "Nehemiah"], respuesta: "Solomon" },
    { tipo: "quiz", pregunta: "Who killed a giant with five smooth stones?", opciones: ["David", "Saul", "Jonathan", "Joshua"], respuesta: "David" },
    { tipo: "versiculo", pregunta: "You are the ____ of the world", opciones: ["light", "salt", "peace", "life"], respuesta: "light" },
    { tipo: "personaje", pistas: ["He had a coat of many colors"], opciones: ["Joseph", "Benjamin", "Reuben", "Judah"], respuesta: "Joseph" },
    { tipo: "quiz", pregunta: "What was Matthew's profession before following Jesus?", opciones: ["Tax collector", "Fisherman", "Carpenter", "Priest"], respuesta: "Tax collector" },
    { tipo: "versiculo", pregunta: "I am the way, the ____ and the life", opciones: ["truth", "light", "door", "peace"], respuesta: "truth" },
    { tipo: "personaje", pistas: ["He was taken up to heaven in a whirlwind"], opciones: ["Elijah", "Enoch", "Moses", "John"], respuesta: "Elijah" },
    { tipo: "quiz", pregunta: "Who wrote most of the New Testament?", opciones: ["Paul", "John", "Peter", "Luke"], respuesta: "Paul" },
    { tipo: "versiculo", pregunta: "Nothing is impossible with ____", opciones: ["God", "man", "faith", "prayer"], respuesta: "God" }
  ],
  pt: [
    { tipo: "quiz", pregunta: "Quem construiu a arca?", opciones: ["Noé", "Moisés", "Abraão", "Davi"], respuesta: "Noé" },
    { tipo: "versiculo", pregunta: "O Senhor é o meu ____; nada me faltará", opciones: ["pastor", "escudo", "guia", "refúgio"], respuesta: "pastor" },
    { tipo: "personaje", pistas: ["Personagem que derrotou Golias"], opciones: ["Davi", "Saul", "Salomão", "Sansón"], respuesta: "Davi" },
    { tipo: "quiz", pregunta: "Quem esteve na cova dos leões?", opciones: ["Daniel", "Pedro", "Paulo", "José"], respuesta: "Daniel" },
    { tipo: "versiculo", pregunta: "A fé vem pelo ____", opciones: ["ouvir", "ver", "sentir", "crer"], respuesta: "ouvir" },
    { tipo: "personaje", pistas: ["Personagem que interpretou sonhos no Egito"], opciones: ["José", "Daniel", "Jacó", "Esaú"], respuesta: "José" },
    { tipo: "quiz", pregunta: "Quem negou a Jesus três vezes?", opciones: ["Pedro", "João", "Judas", "Tomé"], respuesta: "Pedro" },
    { tipo: "versiculo", pregunta: "Peça e ser-lhe-á ____", opciones: ["dado", "tirado", "negado", "aberto"], respuesta: "dado" },
    { tipo: "personaje", pistas: ["Personagem chamado pai da fé"], opciones: ["Abraão", "Noé", "Isaque", "Jacó"], respuesta: "Abraão" },
    { tipo: "quiz", pregunta: "Quem foi a mãe de Jesus?", opciones: ["Maria", "Marta", "Isabel", "Madalena"], respuesta: "Maria" },
    { tipo: "versiculo", pregunta: "Porque Deus amou o ____ de tal maneira", opciones: ["mundo", "homem", "povo", "reino"], respuesta: "mundo" },
    { tipo: "personaje", pistas: ["Personagem que abriu o Mar Vermelho"], opciones: ["Moisés", "Josué", "Arão", "Gideão"], respuesta: "Moisés" },
    { tipo: "quiz", pregunta: "Quem derrotou Golias?", opciones: ["Davi", "Saul", "Jônatas", "Josué"], respuesta: "Davi" },
    { tipo: "versiculo", pregunta: "Lâmpada para os meus pés é a tua ____", opciones: ["palavra", "luz", "lei", "guia"], respuesta: "palavra" },
    { tipo: "personaje", pistas: ["Personagem que foi engolido por um grande peixe"], opciones: ["Jonas", "Noé", "Pedro", "Paulo"], respuesta: "Jonas" },
    { tipo: "quiz", pregunta: "Quem interpretou sonhos no Egito?", opciones: ["José", "Daniel", "Faraó", "Copeiro"], respuesta: "José" },
    { tipo: "versiculo", pregunta: "Bem-aventurados os limpos de ____", opciones: ["coração", "espírito", "alma", "mente"], respuesta: "coração" },
    { tipo: "personaje", pistas: ["Personagem famoso pela sua sabedoria"], opciones: ["Salomão", "Davi", "Eclesiastes", "Jesus"], respuesta: "Salomão" },
    { tipo: "quiz", pregunta: "Quem é chamado pai da fé?", opciones: ["Abraão", "Isaque", "Jacó", "Moisés"], respuesta: "Abraão" },
    { tipo: "versiculo", pregunta: "No princípio criou Deus os ____ e a terra", opciones: ["céus", "mares", "homens", "animais"], respuesta: "céus" },
    { tipo: "quiz", pregunta: "Quem abriu o Mar Vermelho?", opciones: ["Moisés", "Josué", "Arão", "Asher"], respuesta: "Moisés" },
    { tipo: "versiculo", pregunta: "Tudo posso em ____ que me fortalece", opciones: ["Cristo", "Deus", "o Senhor", "o Espírito"], respuesta: "Cristo" },
    { tipo: "quiz", pregunta: "Quem foi engolido por um grande peixe?", opciones: ["Jonas", "Noé", "Pedro", "Paulo"], respuesta: "Jonas" },
    { tipo: "versiculo", pregunta: "O Senhor é a minha luz e a minha ____", opciones: ["salvação", "força", "guia", "refúgio"], respuesta: "salvação" },
    { tipo: "quiz", pregunta: "Quem foi famoso pela sua sabedoria?", opciones: ["Salomão", "Davi", "Roboão", "Josafá"], respuesta: "Salomão" },
    { tipo: "versiculo", pregunta: "O céu e a terra passarão, mas as minhas ____ não passarão", opciones: ["palavras", "leis", "caminhos", "promessas"], respuesta: "palavras" },
    { tipo: "quiz", pregunta: "Quantos anos os israelitas passaram no deserto?", opciones: ["40", "50", "30", "12"], respuesta: "40" },
    { tipo: "versiculo", pregunta: "Clame a mim e eu ____", opciones: ["responderei", "ajudarei", "salvarei", "olharei"], respuesta: "responderei" },
    { tipo: "personaje", pistas: ["Fui lançado na cova dos leões por orar"], opciones: ["Daniel", "Ezequiel", "Jeremias", "Isaías"], respuesta: "Daniel" },
    { tipo: "quiz", pregunta: "Em que cidade Jesus nasceu?", opciones: ["Belém", "Nazaré", "Jerusalém", "Jericó"], respuesta: "Belém" },
    { tipo: "versiculo", pregunta: "Buscai primeiro o reino de ____", opciones: ["Deus", "céu", "paz", "justiça"], respuesta: "Deus" },
    { tipo: "personaje", pistas: ["Fui o homem mais forte da Bíblia"], opciones: ["Sansão", "Golias", "Gedeão", "Davi"], respuesta: "Sansão" },
    { tipo: "quiz", pregunta: "Qual é o primeiro libro da Bíblia?", opciones: ["Gênesis", "Êxodo", "Mateus", "Apocalipse"], respuesta: "Génézis" },
    { tipo: "versiculo", pregunta: "O Senhor é o meu pastor, nada me ____", opciones: ["faltará", "sobrará", "tirará", "negará"], respuesta: "faltará" },
    { tipo: "personaje", pistas: ["Fui o primeiro homem criado"], opciones: ["Adão", "Noé", "Enoque", "Abel"], respuesta: "Adão" },
    { tipo: "quiz", pregunta: "Quem traiu Jesus com um beijo?", opciones: ["Judas", "Pedro", "Tomé", "Mateus"], respuesta: "Judas" },
    { tipo: "versiculo", pregunta: "No princípio era o ____", opciones: ["Verbo", "Mundo", "Homem", "Espírito"], respuesta: "Verbo" },
    { tipo: "personaje", pistas: ["Sofri muito, mas não neguei a Deus"], opciones: ["Jó", "Elias", "Isaías", "Lázaro"], respuesta: "Jó" },
    { tipo: "quiz", pregunta: "Qual é o último libro da Bíblia?", opciones: ["Apocalipse", "Judas", "Hebreos", "Malaquías"], respuesta: "Apocalipse" },
    { tipo: "versiculo", pregunta: "Jesus chorou. (João ____)", opciones: ["11:35", "3:16", "1:1", "14:6"], respuesta: "11:35" },
    { tipo: "quiz", pregunta: "Quem foi o homem que viveu mais anos?", opciones: ["Matusalém", "Enoque", "Noé", "Adão"], respuesta: "Matusalém" },
    { tipo: "versiculo", pregunta: "Cria em mim, ó Deus, um ____ limpo", opciones: ["coração", "espírito", "caminho", "alma"], respuesta: "coração" },
    { tipo: "personaje", pistas: ["Sua esposa se tornou uma estátua de sal"], opciones: ["Ló", "Abraão", "Isaque", "Jacó"], respuesta: "Ló" },
    { tipo: "quiz", pregunta: "A quem Jesus ressuscitou depois de quatro dias?", opciones: ["Lázaro", "Jairo", "Bartimeu", "Nicodemos"], respuesta: "Lázaro" },
    { tipo: "versiculo", pregunta: "Suportando uns aos outros em ____", opciones: ["amor", "paciência", "paz", "fé"], respuesta: "amor" },
    { tipo: "personaje", pistas: ["Fez descer fogo do céu no Monte Carmelo"], opciones: ["Elias", "Eliseu", "Isaías", "Jeremias"], respuesta: "Elias" },
    { tipo: "quiz", pregunta: "Quantas pragas Deus enviou ao Egito?", opciones: ["10", "12", "7", "40"], respuesta: "10" },
    { tipo: "versiculo", pregunta: "O temor do Senhor é o princípio da ____", opciones: ["sabedoria", "fé", "vida", "paz"], respuesta: "sabedoria" },
    { tipo: "personaje", pistas: ["Batizou Jesus no rio Jordão"], opciones: ["João Batista", "Pedro", "Tiago", "Filipe"], respuesta: "João Batista" },
    { tipo: "quiz", pregunta: "Que bebê foi salvo de um rio em uma cesta?", opciones: ["Moisés", "José", "Isaque", "Samuel"], respuesta: "Moisés" },
    { tipo: "versiculo", pregunta: "Mas o fruto do Espírito é ____", opciones: ["amor", "fé", "poder", "sabedoria"], respuesta: "amor" },
    { tipo: "personaje", pistas: ["Construiu o Templo de Jerusalém"], opciones: ["Salomão", "Davi", "Esdras", "Neemias"], respuesta: "Salomão" },
    { tipo: "quiz", pregunta: "Quem matou um gigante com cinco pedras lisas?", opciones: ["Davi", "Saul", "Jônatas", "Josué"], respuesta: "Davi" },
    { tipo: "versiculo", pregunta: "Vós sois a ____ do mundo", opciones: ["luz", "sal", "paz", "vida"], respuesta: "luz" },
    { tipo: "personaje", pistas: ["Teve uma túnica de muitas cores"], opciones: ["José", "Benjamim", "Rúben", "Judá"], respuesta: "José" },
    { tipo: "quiz", pregunta: "Qual era a profissão de Mateus antes de seguir Jesus?", opciones: ["Publicano", "Pescador", "Carpinteiro", "Sacerdote"], respuesta: "Publicano" },
    { tipo: "versiculo", pregunta: "Eu sou o caminho, a ____ e a vida", opciones: ["verdade", "luz", "porta", "paz"], respuesta: "verdade" },
    { tipo: "personaje", pistas: ["Foi levado ao céu em um redemoinho"], opciones: ["Elias", "Enoque", "Moisés", "João"], respuesta: "Elias" },
    { tipo: "quiz", pregunta: "Quem escreveu a maior parte do Novo Testamento?", opciones: ["Paulo", "João", "Pedro", "Lucas"], respuesta: "Paulo" },
    { tipo: "versiculo", pregunta: "Nada é impossível para ____", opciones: ["Deus", "o homem", "a fé", "a oração"], respuesta: "Deus" }
  ],
  it: [
    { tipo: "quiz", pregunta: "Chi ha costruito l'arca?", opciones: ["Noè", "Mosè", "Abramo", "Davide"], respuesta: "Noè" },
    { tipo: "versiculo", pregunta: "Il Signore è il mio ____; non manco di nulla", opciones: ["pastore", "scudo", "guida", "rifugio"], respuesta: "pastore" },
    { tipo: "personaje", pistas: ["Personaggio che ha sconfitto Golia"], opciones: ["Davide", "Saul", "Salomone", "Sansone"], respuesta: "Davide" },
    { tipo: "quiz", pregunta: "Chi era nella fossa dei leoni?", opciones: ["Daniele", "Pietro", "Paolo", "Giuseppe"], respuesta: "Daniele" },
    { tipo: "versiculo", pregunta: "La fede viene dall'____", opciones: ["ascolto", "vedere", "sentire", "credere"], respuesta: "ascolto" },
    { tipo: "personaje", pistas: ["Personaggio che interpretava i sogni in Egitto"], opciones: ["Giuseppe", "Daniele", "Giacobbe", "Esaù"], respuesta: "Giuseppe" },
    { tipo: "quiz", pregunta: "Chi ha rinnegato Gesù tre volte?", opciones: ["Pietro", "Giovanni", "Giuda", "Tommaso"], respuesta: "Pietro" },
    { tipo: "versiculo", pregunta: "Chiedete e vi sarà ____", opciones: ["dato", "tolto", "negato", "aperto"], respuesta: "dato" },
    { tipo: "personaje", pistas: ["Personaggio chiamato padre della fede"], opciones: ["Abramo", "Noè", "Isacco", "Giacobbe"], respuesta: "Abramo" },
    { tipo: "quiz", pregunta: "Chi era la madre di Gesù?", opciones: ["Maria", "Marta", "Elisabetta", "Maddalena"], respuesta: "Maria" },
    { tipo: "versiculo", pregunta: "Perché Dio ha tanto amato il ____", opciones: ["mondo", "uomo", "popolo", "regno"], respuesta: "mondo" },
    { tipo: "personaje", pistas: ["Personaggio che ha diviso il Mar Rosso"], opciones: ["Mosè", "Giosuè", "Aronne", "Gedeone"], respuesta: "Mosè" },
    { tipo: "quiz", pregunta: "Chi ha sconfitto Golia?", opciones: ["Davide", "Saul", "Gionata", "Giosuè"], respuesta: "Davide" },
    { tipo: "versiculo", pregunta: "Lampada per i miei passi è la tua ____", opciones: ["parola", "luce", "legge", "guida"], respuesta: "parola" },
    { tipo: "personaje", pistas: ["Personaggio inghiottito da un grande pesce"], opciones: ["Giona", "Noè", "Pietro", "Paolo"], respuesta: "Giona" },
    { tipo: "quiz", pregunta: "Chi interpretava i sogni in Egitto?", opciones: ["Giuseppe", "Daniele", "Faraone", "Coppiere"], respuesta: "Giuseppe" },
    { tipo: "versiculo", pregunta: "Beati i puri di ____", opciones: ["cuore", "spirito", "anima", "mente"], respuesta: "cuore" },
    { tipo: "personaje", pistas: ["Personaggio famoso per la saggezza"], opciones: ["Salomone", "Davide", "Ecclesiaste", "Gesù"], respuesta: "Salomone" },
    { tipo: "quiz", pregunta: "Chi è chiamato padre della fede?", opciones: ["Abramo", "Isacco", "Giacobbe", "Mosè"], respuesta: "Abramo" },
    { tipo: "versiculo", pregunta: "Nel principio Dio creò i ____ e la terra", opciones: ["cieli", "mari", "uomini", "animali"], respuesta: "cieli" },
    { tipo: "quiz", pregunta: "Chi ha diviso il Mar Rosso?", opciones: ["Mosè", "Giosuè", "Aronne", "Aser"], respuesta: "Mosè" },
    { tipo: "versiculo", pregunta: "Tutto posso in ____ che mi dà forza", opciones: ["Cristo", "Dio", "il Signore", "lo Spirito"], respuesta: "Cristo" },
    { tipo: "quiz", pregunta: "Chi fu inghiottito da un grande pesce?", opciones: ["Giona", "Noè", "Pietro", "Paolo"], respuesta: "Giona" },
    { tipo: "versiculo", pregunta: "Il Signore è la mia luce e la mia ____", opciones: ["salvezza", "forza", "guida", "rifugio"], respuesta: "salvezza" },
    { tipo: "quiz", pregunta: "Chi fu famoso per la sua saggezza?", opciones: ["Salomone", "Davide", "Roboamo", "Giosafat"], respuesta: "Salomone" },
    { tipo: "versiculo", pregunta: "Il cielo e la terra passeranno, ma le mie ____ non passeranno", opciones: ["parole", "leggi", "vie", "promesse"], respuesta: "parole" },
    { tipo: "quiz", pregunta: "Quanti anni trascorsero gli Israeliti nel deserto?", opciones: ["40", "50", "30", "12"], respuesta: "40" },
    { tipo: "versiculo", pregunta: "Invocami e io ti ____", opciones: ["risponderò", "aiuterò", "salverò", "guarderò"], respuesta: "risponderò" },
    { tipo: "personaje", pistas: ["Fui gettato nella fossa dei leoni perché pregavo"], opciones: ["Daniele", "Ezechiele", "Geremia", "Isaia"], respuesta: "Daniele" },
    { tipo: "quiz", pregunta: "In quale città è nato Gesù?", opciones: ["Betlemme", "Nazaret", "Gerusalemme", "Gerico"], respuesta: "Betlemme" },
    { tipo: "versiculo", pregunta: "Cercate prima il regno di ____", opciones: ["Dio", "cielo", "pace", "giustizia"], respuesta: "Dio" },
    { tipo: "personaje", pistas: ["Ero l'uomo più forte della Bibbia"], opciones: ["Sansone", "Golia", "Gedeone", "Davide"], respuesta: "Sansone" },
    { tipo: "quiz", pregunta: "Qual è il primo libro della Bibbia?", opciones: ["Genesi", "Esodo", "Matteo", "Apocalisse"], respuesta: "Genesi" },
    { tipo: "versiculo", pregunta: "Il Signore è il mio pastore, non ____ di nulla", opciones: ["manco", "spreco", "perdo", "nego"], respuesta: "manco" },
    { tipo: "personaje", pistas: ["Fui il primo uomo creato"], opciones: ["Adamo", "Noè", "Enoc", "Abele"], respuesta: "Adamo" },
    { tipo: "quiz", pregunta: "Chi tradì Gesù con un bacio?", opciones: ["Giuda", "Pietro", "Tommaso", "Matteo"], respuesta: "Giuda" },
    { tipo: "versiculo", pregunta: "In principio era il ____", opciones: ["Verbo", "Mondo", "Uomo", "Spirito"], respuesta: "Verbo" },
    { tipo: "personaje", pistas: ["Soffrii molto ma non rinnegai Dio"], opciones: ["Giobbe", "Elia", "Isaia", "Lazzaro"], respuesta: "Giobbe" },
    { tipo: "quiz", pregunta: "Qual è l'ultimo libro della Bibbia?", opciones: ["Apocalisse", "Giuda", "Ebrei", "Malachia"], respuesta: "Apocalisse" },
    { tipo: "versiculo", pregunta: "Gesù pianse. (Giovanni ____)", opciones: ["11:35", "3:16", "1:1", "14:6"], respuesta: "11:35" },
    { tipo: "quiz", pregunta: "Chi fu l'uomo che visse più a lungo?", opciones: ["Matusalemme", "Enoc", "Noè", "Adamo"], respuesta: "Matusalemme" },
    { tipo: "versiculo", pregunta: "Crea in me, o Dio, un ____ puro", opciones: ["cuore", "spirito", "cammino", "anima"], respuesta: "cuore" },
    { tipo: "personaje", pistas: ["Sua moglie diventò una statua di sale"], opciones: ["Lot", "Abramo", "Isacco", "Giacobbe"], respuesta: "Lot" },
    { tipo: "quiz", pregunta: "Chi risuscitò Gesù dopo quattro giorni?", opciones: ["Lazzaro", "Iairo", "Bartimeo", "Nicodemo"], respuesta: "Lazzaro" },
    { tipo: "versiculo", pregunta: "Sopportandovi gli uni gli altri con ____", opciones: ["amore", "pazienza", "pace", "fede"], respuesta: "amore" },
    { tipo: "personaje", pistas: ["Fece scendere fuoco dal cielo sul monte Carmelo"], opciones: ["Elia", "Eliseo", "Isaia", "Geremia"], respuesta: "Elia" },
    { tipo: "quiz", pregunta: "Quante piaghe mandò Dio in Egitto?", opciones: ["10", "12", "7", "40"], respuesta: "10" },
    { tipo: "versiculo", pregunta: "Il timore del Signore è il principio della ____", opciones: ["saggezza", "fede", "vita", "pace"], respuesta: "saggezza" },
    { tipo: "personaje", pistas: ["Battezzò Gesù nel fiume Giordano"], opciones: ["Giovanni Battista", "Pietro", "Giacomo", "Filippo"], respuesta: "Giovanni Battista" },
    { tipo: "quiz", pregunta: "Quale bambino fu salvato da un fiume in un canestro?", opciones: ["Mosè", "Giuseppe", "Isacco", "Samuele"], respuesta: "Mosè" },
    { tipo: "versiculo", pregunta: "Ma il frutto dello Spirito è ____", opciones: ["amore", "fede", "potere", "saggezza"], respuesta: "amore" },
    { tipo: "personaje", pistas: ["Costruì il Tempio a Gerusalemme"], opciones: ["Salomone", "Davide", "Esdra", "Neemia"], respuesta: "Salomone" },
    { tipo: "quiz", pregunta: "Chi uccise un gigante con cinque pietre lisce?", opciones: ["Davide", "Saul", "Gionata", "Giosuè"], respuesta: "Davide" },
    { tipo: "versiculo", pregunta: "Voi siete la ____ del mondo", opciones: ["luce", "sale", "pace", "vita"], respuesta: "luce" },
    { tipo: "personaje", pistas: ["Ebbe una tunica di molti colori"], opciones: ["Giuseppe", "Beniamino", "Ruben", "Giuda"], respuesta: "Giuseppe" },
    { tipo: "quiz", pregunta: "Qual era la professione di Matteo prima di seguire Gesù?", opciones: ["Pubblicano", "Pescatore", "Falegname", "Sacerdote"], respuesta: "Pubblicano" },
    { tipo: "versiculo", pregunta: "Io sono la via, la ____ e la vita", opciones: ["verità", "luce", "porta", "pace"], respuesta: "verità" },
    { tipo: "personaje", pistas: ["Fu rapito in cielo in un turbine"], opciones: ["Elia", "Enoc", "Mosè", "Giovanni"], respuesta: "Elia" },
    { tipo: "quiz", pregunta: "Chi scrisse la maggior parte del Nuovo Testamento?", opciones: ["Paolo", "Giovanni", "Pietro", "Luca"], respuesta: "Paolo" },
    { tipo: "versiculo", pregunta: "Nulla è impossibile a ____", opciones: ["Dio", "uomo", "fede", "preghiera"], respuesta: "Dio" }
  ],
  de: [
    { tipo: "quiz", pregunta: "Wer baute die Arche?", opciones: ["Noah", "Mose", "Abraham", "David"], respuesta: "Noah" },
    { tipo: "versiculo", pregunta: "Der Herr ist mein ____; mir wird nichts mangeln", opciones: ["Hirte", "Schild", "Führer", "Zuflucht"], respuesta: "Hirte" },
    { tipo: "personaje", pistas: ["Person, die Goliath besiegte"], opciones: ["David", "Saul", "Salomo", "Simson"], respuesta: "David" },
    { tipo: "quiz", pregunta: "Wer war in der Löwengrube?", opciones: ["Daniel", "Petrus", "Paulus", "Josef"], respuesta: "Daniel" },
    { tipo: "versiculo", pregunta: "Der Glaube kommt aus dem ____", opciones: ["Hören", "Sehen", "Fühlen", "Glauben"], respuesta: "Hören" },
    { tipo: "personaje", pistas: ["Person, die Träume in Ägypten deutete"], opciones: ["Josef", "Daniel", "Jakob", "Esau"], respuesta: "Josef" },
    { tipo: "quiz", pregunta: "Wer verleugnete Jesus dreimal?", opciones: ["Petrus", "Johannes", "Judas", "Thomas"], respuesta: "Petrus" },
    { tipo: "versiculo", pregunta: "Bittet, so wird euch ____", opciones: ["gegeben", "genommen", "verweigert", "geöffnet"], respuesta: "gegeben" },
    { tipo: "personaje", pistas: ["Person, der Vater des Glaubens genannt wird"], opciones: ["Abraham", "Noah", "Isaak", "Jakob"], respuesta: "Abraham" },
    { tipo: "quiz", pregunta: "Wer war die Mutter Jesu?", opciones: ["Maria", "Martha", "Elisabeth", "Magdalena"], respuesta: "Maria" },
    { tipo: "versiculo", pregunta: "Denn also hat Gott die ____ geliebt", opciones: ["Welt", "Mensch", "Volk", "Königreich"], respuesta: "Welt" },
    { tipo: "personaje", pistas: ["Person, die das Rote Meer teilte"], opciones: ["Mose", "Josua", "Aaron", "Gideon"], respuesta: "Mose" },
    { tipo: "quiz", pregunta: "Wer besiegte Goliath?", opciones: ["David", "Saul", "Jonathan", "Josua"], respuesta: "David" },
    { tipo: "versiculo", pregunta: "Dein ____ ist meines Fußes Leuchte", opciones: ["Wort", "Licht", "Gesetz", "Leitfaden"], respuesta: "Wort" },
    { tipo: "personaje", pistas: ["Person, die von einem großen Fisch verschluckt wurde"], opciones: ["Jona", "Noah", "Petrus", "Paulus"], respuesta: "Jona" },
    { tipo: "quiz", pregunta: "Wer deutete Träume in Ägypten?", opciones: ["Josef", "Daniel", "Pharao", "Schenke"], respuesta: "Josef" },
    { tipo: "versiculo", pregunta: "Selig sind, die reinen ____ sind", opciones: ["Herzens", "Geistes", "Seele", "Verstandes"], respuesta: "Herzens" },
    { tipo: "personaje", pistas: ["Person, berühmt für Weisheit"], opciones: ["Salomo", "David", "Prediger", "Jesus"], respuesta: "Salomo" },
    { tipo: "quiz", pregunta: "Wer wird Vater des Glaubens genannt?", opciones: ["Abraham", "Isaak", "Jakob", "Mose"], respuesta: "Abraham" },
    { tipo: "versiculo", pregunta: "Am Anfang schuf Gott die ____ und die Erde", opciones: ["Himmel", "Meere", "Menschen", "Tiere"], respuesta: "Himmel" },
    { tipo: "quiz", pregunta: "Wer teilte das Rote Meer?", opciones: ["Mose", "Josua", "Aaron", "Ascher"], respuesta: "Mose" },
    { tipo: "versiculo", pregunta: "Alles vermag ich durch ____, der mich stärkt", opciones: ["Christus", "Gott", "den Herrn", "den Geist"], respuesta: "Christus" },
    { tipo: "quiz", pregunta: "Wer wurde von einem großen Fisch verschluckt?", opciones: ["Jona", "Noah", "Petrus", "Paulus"], respuesta: "Jona" },
    { tipo: "versiculo", pregunta: "Der Herr ist mein Licht und mein ____", opciones: ["Heil", "Stärke", "Führer", "Zuflucht"], respuesta: "Heil" },
    { tipo: "quiz", pregunta: "Wer war berühmt für seine Weisheit?", opciones: ["Salomo", "David", "Rehabeam", "Josaphat"], respuesta: "Salomo" },
    { tipo: "versiculo", pregunta: "Himmel und Erde werden vergehen, aber meine ____ werden nicht vergehen", opciones: ["Worte", "Gesetze", "Wege", "Versprechen"], respuesta: "Worte" },
    { tipo: "quiz", pregunta: "Wie viele Jahre verbrachten die Israeliten in der Wüste?", opciones: ["40", "50", "30", "12"], respuesta: "40" },
    { tipo: "versiculo", pregunta: "Rufe mich an, so will ich dir ____", opciones: ["antworten", "helfen", "retten", "sehen"], respuesta: "antworten" },
    { tipo: "personaje", pistas: ["Ich wurde in eine Löwengrube geworfen, weil ich betete"], opciones: ["Daniel", "Hesekiel", "Jeremia", "Jesaja"], respuesta: "Daniel" },
    { tipo: "quiz", pregunta: "In welcher Stadt wurde Jesus geboren?", opciones: ["Bethlehem", "Nazareth", "Jerusalem", "Jericho"], respuesta: "Bethlehem" },
    { tipo: "versiculo", pregunta: "Trachtet zuerst nach dem Reich ____", opciones: ["Gottes", "des Himmels", "Frieden", "Gerechtigkeit"], respuesta: "Gottes" },
    { tipo: "personaje", pistas: ["Ich war der stärkste Mann in der Bibel"], opciones: ["Simson", "Goliath", "Gideon", "David"], respuesta: "Simson" },
    { tipo: "quiz", pregunta: "Was ist das erste Buch der Bibel?", opciones: ["Genesis", "Exodus", "Matthäus", "Offenbarung"], respuesta: "Genesis" },
    { tipo: "versiculo", pregunta: "Der Herr ist mein Hirte, mir wird nichts ____", opciones: ["mangeln", "fehlen", "bleiben", "verweigert"], respuesta: "mangeln" },
    { tipo: "personaje", pistas: ["Ich war der erste erschaffene Mensch"], opciones: ["Adam", "Noah", "Enoch", "Abel"], respuesta: "Adam" },
    { tipo: "quiz", pregunta: "Wer verriet Jesus mit einem Kuss?", opciones: ["Judas", "Petrus", "Thomas", "Matthäus"], respuesta: "Judas" },
    { tipo: "versiculo", pregunta: "Im Anfang war das ____", opciones: ["Wort", "Welt", "Mensch", "Geist"], respuesta: "Wort" },
    { tipo: "personaje", pistas: ["Ich litt viel, aber verleugnete Gott nicht"], opciones: ["Hiob", "Elia", "Jesaja", "Lazarus"], respuesta: "Hiob" },
    { tipo: "quiz", pregunta: "Was ist das letzte Buch der Bibel?", opciones: ["Offenbarung", "Judas", "Hebräer", "Maleachi"], respuesta: "Offenbarung" },
    { tipo: "versiculo", pregunta: "Jesus weinte. (Johannes ____)", opciones: ["11:35", "3:16", "1:1", "14:6"], respuesta: "11:35" },
    { tipo: "quiz", pregunta: "Wer war der älteste Mann in der Bibel?", opciones: ["Methusalah", "Enoch", "Noah", "Adam"], respuesta: "Methusalah" },
    { tipo: "versiculo", pregunta: "Schaffe in mir, Gott, ein reines ____", opciones: ["Herz", "Geist", "Weg", "Seele"], respuesta: "Herz" },
    { tipo: "personaje", pistas: ["Seine Frau wurde zur Salzpfeiler"], opciones: ["Lot", "Abraham", "Isaak", "Jakob"], respuesta: "Lot" },
    { tipo: "quiz", pregunta: "Wen erweckte Jesus nach vier Tagen von den Toten auf?", opciones: ["Lazarus", "Jairus", "Bartimäus", "Nikodemus"], respuesta: "Lazarus" },
    { tipo: "versiculo", pregunta: "Ertrag einer den andern in ____", opciones: ["Liebe", "Geduld", "Frieden", "Glauben"], respuesta: "Liebe" },
    { tipo: "personaje", pistas: ["Er ließ Feuer vom Himmel fallen auf dem Berg Karmel"], opciones: ["Elia", "Elisa", "Jesaja", "Jeremia"], respuesta: "Elia" },
    { tipo: "quiz", pregunta: "Wie viele Plagen schickte Gott nach Ägypten?", opciones: ["10", "12", "7", "40"], respuesta: "10" },
    { tipo: "versiculo", pregunta: "Die Furcht des Herrn ist der Anfang der ____", opciones: ["Weisheit", "Glauben", "Leben", "Frieden"], respuesta: "Weisheit" },
    { tipo: "personaje", pistas: ["Er taufte Jesus im Jordan"], opciones: ["Johannes der Täufer", "Petrus", "Jakobus", "Philippus"], respuesta: "Johannes der Täufer" },
    { tipo: "quiz", pregunta: "Welches Baby wurde in einem Korb aus einem Fluss gerettet?", opciones: ["Mose", "Josef", "Isaak", "Samuel"], respuesta: "Mose" },
    { tipo: "versiculo", pregunta: "Aber die Frucht des Geistes ist ____", opciones: ["Liebe", "Glaube", "Kraft", "Weisheit"], respuesta: "Liebe" },
    { tipo: "personaje", pistas: ["Er baute den Tempel in Jerusalem"], opciones: ["Salomo", "David", "Esra", "Nehemia"], respuesta: "Salomo" },
    { tipo: "quiz", pregunta: "Wer tötete einen Riesen mit fünf glatten Steinen?", opciones: ["David", "Saul", "Jonathan", "Josua"], respuesta: "David" },
    { tipo: "versiculo", pregunta: "Ihr seid das ____ der Welt", opciones: ["Licht", "Salz", "Frieden", "Leben"], respuesta: "Licht" },
    { tipo: "personaje", pistas: ["Er hatte einen bunten Rock"], opciones: ["Josef", "Benjamin", "Ruben", "Juda"], respuesta: "Josef" },
    { tipo: "quiz", pregunta: "Was war Matthäus' Beruf, bevor er Jesus folgte?", opciones: ["Zöllner", "Fischer", "Zimmermann", "Priester"], respuesta: "Zöllner" },
    { tipo: "versiculo", pregunta: "Ich bin der Weg, die ____ und das Leben", opciones: ["Wahrheit", "Licht", "Tür", "Frieden"], respuesta: "Wahrheit" },
    { tipo: "personaje", pistas: ["Er wurde im Wirbelsturm zum Himmel aufgenommen"], opciones: ["Elia", "Enoch", "Mose", "Johannes"], respuesta: "Elia" },
    { tipo: "quiz", pregunta: "Wer schrieb den größten Teil des Neuen Testaments?", opciones: ["Paulus", "Johannes", "Petrus", "Lukas"], respuesta: "Paulus" },
    { tipo: "versiculo", pregunta: "Bei ____ ist kein Ding unmöglich", opciones: ["Gott", "Menschen", "Glauben", "Gebet"], respuesta: "Gott" }
  ]
};
